{ mkDerivation, base, bytestring, containers, glib, stdenv, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.21.5";
  sha256 = "f04d372ce57821f84524d7191b769ee2ae7f14dd1db5c306cadd771625e5b6df";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = stdenv.lib.licenses.lgpl21;
}
